# Generated by Django 5.1.3 on 2024-11-17 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=15)),
                ('height', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(blank=True, choices=[('1А', '1А'), ('2А', '2А'), ('3А', '3А'), ('1B', '1Б'), ('2B', '2Б'), ('3B', '3Б'), ('3B*', '3Б*')], max_length=3, null=True)),
                ('summer', models.CharField(blank=True, choices=[('1А', '1А'), ('2А', '2А'), ('3А', '3А'), ('1B', '1Б'), ('2B', '2Б'), ('3B', '3Б'), ('3B*', '3Б*')], max_length=3, null=True)),
                ('autumn', models.CharField(blank=True, choices=[('1А', '1А'), ('2А', '2А'), ('3А', '3А'), ('1B', '1Б'), ('2B', '2Б'), ('3B', '3Б'), ('3B*', '3Б*')], max_length=3, null=True)),
                ('spring', models.CharField(blank=True, choices=[('1А', '1А'), ('2А', '2А'), ('3А', '3А'), ('1B', '1Б'), ('2B', '2Б'), ('3B', '3Б'), ('3B*', '3Б*')], max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('fam', models.CharField(default='Иванов', max_length=50)),
                ('name', models.CharField(default='Иван', max_length=50)),
                ('otc', models.CharField(default='Иванович', max_length=50)),
                ('phone', models.CharField(default='8 999 999 99 99', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(default='пер.', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('other_titles', models.CharField(blank=True, max_length=255, null=True)),
                ('connect', models.CharField(blank=True, max_length=255, null=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('new', 'new')], default='new', max_length=8)),
                ('coords', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coords', to='project.coordinates')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level', to='project.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='project.user')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ImageField(blank=True, null=True, upload_to='pereval/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='project.pereval')),
            ],
        ),
    ]
