# Generated by Django 5.1.3 on 2024-11-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='8 999 999 99 99', max_length=17),
        ),
    ]
